<a href="https://colab.research.google.com/github/ducnd58233/helmet-detection-yolov10/blob/main/Helmet_Detection_YOLOv10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Setup

In [ ]:
!git clone https://github.com/THU-MIG/yolov10.git

Cloning into 'yolov10'...
remote: Enumerating objects: 20304, done.
remote: Counting objects: 100% (1502/1502), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 20304 (delta 1438), reused 1348 (delta 1348), pack-reused 18802
Receiving objects: 100% (20304/20304), 11.17 MiB | 11.27 MiB/s, done.
Resolving deltas: 100% (14314/14314), done.


In [ ]:
%cd yolov10
!pip install -q -r requirements.txt
!pip install -e .

/content/yolov10
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 83.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 91.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 68.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 426.2/426.2 kB 43.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 90.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.8/199.8 MB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 106.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 34.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.7/401.7 kB 42.5 MB/s eta 0:00:00
     ━━━

In [ ]:
!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt

--2024-07-02 16:31:41--  https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/804788522/411e0d4f-1023-40ad-bfdd-c99f0dddb73b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240702%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240702T163141Z&X-Amz-Expires=300&X-Amz-Signature=169c2f964bebf362c0d6367d8fb1142cb60c2796186166b227023697df1692cf&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=804788522&response-content-disposition=attachment%3B%20filename%3Dyolov10n.pt&response-content-type=application%2Foctet-stream [following]
--2024-07-02 16:31:41--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/804788522/411e0d4f-1023-40ad-bfdd-c99f0dddb73b?X-Amz-Algorit

In [ ]:
!pip install pytube

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 1.9 MB/s eta 0:00:00


In [ ]:
!gdown '1tr9PSRRdlC2pNir7jsYugpSMG-7v32VJ'  -O './images/'

Downloading...
From: https://drive.google.com/uc?id=1tr9PSRRdlC2pNir7jsYugpSMG-7v32VJ
To: /content/yolov10/images/HCMC_Street.jpg
100% 374k/374k [00:00<00:00, 101MB/s]


#Build model

In [ ]:
from ultralytics import YOLOv10

MODEL_PATH = 'yolov10n.pt'
model = YOLOv10(MODEL_PATH)

#Predict

In [ ]:
IMG_PATH = './images/HCMC_Street.jpg'
result = model(source=IMG_PATH)[0]


image 1/1 /content/yolov10/images/HCMC_Street.jpg: 448x640 11 persons, 2 bicycles, 1 car, 2 motorcycles, 62.7ms
Speed: 15.3ms preprocess, 62.7ms inference, 3.0ms postprocess per image at shape (1, 3, 448, 640)


In [ ]:
result.save('./images/HCMC_Street_predict.png')

'./images/HCMC_Street_predict.png'

In [ ]:
YOUTUBE_VIDEO_PATH = 'https://youtu.be/wqPSsu7XQ74'

video_result = model(source=YOUTUBE_VIDEO_PATH, stream=True, save=True)

#Fine-Tuning

In [ ]:
%cd /content/
!gdown '1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R'
!mkdir safety_helmet_dataset
!unzip -q '/content/Safety_Helmet_Dataset.zip' -d '/content/safety_helmet_dataset'

/content
Downloading...
From (original): https://drive.google.com/uc?id=1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R
From (redirected): https://drive.google.com/uc?id=1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R&confirm=t&uuid=85a21fea-f849-4562-a42d-50365dbc8ea3
To: /content/Safety_Helmet_Dataset.zip
100% 33.7M/33.7M [00:00<00:00, 202MB/s]


In [ ]:
import torch

YAML_PATH = '/content/safety_helmet_dataset/data.yaml'
EPOCHS = 10
IMG_SIZE = 640
BATCH_SIZE = 16

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)

model.train(data=YAML_PATH, epochs=EPOCHS, imgsz=IMG_SIZE, batch=BATCH_SIZE)

New https://pypi.org/project/ultralytics/8.2.48 available 😃 Update with 'pip install -U ultralytics'
engine/trainer: task=detect, mode=train, model=yolov10n.pt, data=/content/safety_helmet_dataset/data.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, val_period=1, cache=False, device=cuda:0, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=F

100%|██████████| 755k/755k [00:00<00:00, 95.5MB/s]


Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1      9856  ultralytics.nn.modules.block.SCDown          [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1     36096  ultralytics

100%|██████████| 6.23M/6.23M [00:00<00:00, 298MB/s]


AMP: checks passed ✅


train: Scanning /content/safety_helmet_dataset/train/labels... 761 images, 0 backgrounds, 0 corrupt: 100%|██████████| 761/761 [00:00<00:00, 1924.26it/s]


train: New cache created: /content/safety_helmet_dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
val: Scanning /content/safety_helmet_dataset/valid/labels... 218 images, 0 backgrounds, 0 corrupt: 100%|██████████| 218/218 [00:00<00:00, 1116.62it/s]


val: New cache created: /content/safety_helmet_dataset/valid/labels.cache
Plotting labels to /content/yolov10/runs/detect/train/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 95 weight(decay=0.0), 108 weight(decay=0.0005), 107 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/yolov10/runs/detect/train
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       1/10      3.38G      2.628      3.678      2.913      2.254        7.3        2.6         26        640: 100%|██████████| 48/48 [00:21<00:00,  2.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.60it/s]

                   all        218        586    0.00839      0.337     0.0456     0.0161



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       2/10      3.23G      2.094      2.431      2.191       1.82      5.633      1.989         24        640: 100%|██████████| 48/48 [00:15<00:00,  3.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  1.88it/s]

                   all        218        586      0.699      0.135      0.212     0.0944



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       3/10      3.23G       1.87      1.991       1.96      1.694      4.609      1.785         19        640: 100%|██████████| 48/48 [00:15<00:00,  3.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.20it/s]

                   all        218        586      0.661      0.323      0.334      0.161



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       4/10      3.25G        1.8      1.784      1.875       1.67      3.949      1.737         23        640: 100%|██████████| 48/48 [00:16<00:00,  2.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.36it/s]

                   all        218        586      0.713      0.355      0.406      0.194



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       5/10      3.23G      1.724       1.63      1.789      1.635      3.365      1.662         27        640: 100%|██████████| 48/48 [00:17<00:00,  2.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  3.17it/s]

                   all        218        586      0.704      0.415      0.446      0.211



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       6/10      3.23G       1.67      1.499      1.723      1.605        2.9       1.63         24        640: 100%|██████████| 48/48 [00:17<00:00,  2.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  3.15it/s]

                   all        218        586      0.758        0.4      0.489      0.249



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       7/10      3.23G       1.64      1.432       1.69      1.573      2.631      1.583         23        640: 100%|██████████| 48/48 [00:17<00:00,  2.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  3.05it/s]

                   all        218        586      0.756      0.422      0.536      0.258



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       8/10      3.23G      1.572      1.342      1.633      1.529       2.36      1.535         24        640: 100%|██████████| 48/48 [00:17<00:00,  2.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  3.14it/s]

                   all        218        586      0.759       0.45      0.563      0.284



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


       9/10      3.23G      1.541      1.239      1.586      1.511      2.155      1.516         20        640: 100%|██████████| 48/48 [00:16<00:00,  2.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  3.23it/s]

                   all        218        586      0.781       0.45      0.601      0.313



      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size


      10/10      3.23G       1.51      1.172      1.567      1.489      2.027      1.499         20        640: 100%|██████████| 48/48 [00:16<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  3.00it/s]

                   all        218        586       0.68      0.583      0.643      0.331



10 epochs completed in 0.071 hours.
Optimizer stripped from /content/yolov10/runs/detect/train/weights/last.pt, 5.7MB
Optimizer stripped from /content/yolov10/runs/detect/train/weights/best.pt, 5.7MB

Validating /content/yolov10/runs/detect/train/weights/best.pt...
Ultralytics YOLOv8.1.34 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 15102MiB)
YOLOv10n summary (fused): 285 layers, 2695586 parameters, 0 gradients, 8.2 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:06<00:00,  1.02it/s]


                   all        218        586      0.681      0.583      0.643      0.331
                  head        218         27          1      0.109      0.428      0.208
                helmet        218        285      0.532      0.839      0.784      0.395
                person        218        274      0.509      0.803      0.718      0.389
Speed: 5.9ms preprocess, 7.5ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/yolov10/runs/detect/train


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f8e65f34580>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.04

##Evaluate Fine-tuning model

In [ ]:
TRAINED_MODEL_PATH='/content/yolov10/runs/detect/train/weights/best.pt'
model = YOLOv10(TRAINED_MODEL_PATH)
model.val(data=YAML_PATH,imgsz=IMG_SIZE,split='test')


Ultralytics YOLOv8.1.34 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 15102MiB)
YOLOv10n summary (fused): 285 layers, 2695586 parameters, 0 gradients, 8.2 GFLOPs


val: Scanning /content/safety_helmet_dataset/test/labels... 109 images, 0 backgrounds, 0 corrupt: 100%|██████████| 109/109 [00:00<00:00, 1991.62it/s]

val: New cache created: /content/safety_helmet_dataset/test/labels.cache



/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.43it/s]


                   all        109        320      0.488      0.627      0.615      0.322
                  head        109         16      0.581      0.188      0.356      0.157
                helmet        109        162      0.454      0.883      0.782      0.405
                person        109        142       0.43       0.81      0.708      0.403
Speed: 3.6ms preprocess, 9.0ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/yolov10/runs/detect/val


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f8e5665c550>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.04

In [ ]:
from pytube import YouTube

YOUTUBE_VIDEO_PATH = 'https://youtu.be/wqPSsu7XQ74'
yt = YouTube(YOUTUBE_VIDEO_PATH)
stream = yt.streams.filter(file_extension='mp4').first()
video_path = stream.download('/content')

# Make predictions on the video
results = model(source=video_path, stream=True, save=True, show=True)

# Extract the outputs
for result in results:
    outputs = result.boxes.xyxy
    print(outputs)

WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()


video 1/1 (frame 1/1183) /content/How to cross a street in Ho Chi Minh City (Saigon) Vietnam.mp4: 384x640 1 person, 88.7ms
tensor([[ 10.9303,  51.1845, 127.7373, 321.5482]], device='cuda:0')
video 1/1 (frame 2/1183) /content/How to cross a street in Ho Chi Minh City (Saigon) Vietnam.mp4: 384x640 1 person, 13.0ms
tensor([[  9.4336,  42.6250, 142.4913, 319.8642]], device='cuda:0')
video 1/1 (frame 3/1183) /content/How to cross a street in Ho Chi Minh City (Saigon) Vietnam.mp4: 384x640 1 helmet, 12.9ms
tensor([[  2.2140,  49.7166,  79.9297, 124.3138]], device='cuda:0')
video 1/1 (frame 4/1183) /content/How to cross a street in Ho Chi Minh City (Saigon) Vietnam.mp4: 384x640 1 helmet, 17.0ms
tensor([[ 14.6950,  48.7980,  95.2246, 127.1871]], device='cuda:0')
video 1/1 (frame 5/1183) /content/How to cross a street in Ho Chi Minh City (Saigon) Vietnam.mp4: 384x640 1 helmet, 12.0ms
tensor([[ 29.6924,  48.3325, 109.7285,